<head>
    <title>Stubees</title>
 
	<script>
	/*FB.logout(function(response) {
		<?php Zend_Session::destroy( true ); ?>
		//window.location.reload();
	});
*/

	$( document ).ready(function() {
		$.ajaxSetup ({
			cache: false
		});

		$("#loginButton").click(function(){
			$.ajax({url:"/Login", 
				
			}).done(function(result){ 

				$("#formSlot").html(result);

			})
			.fail(function(response, status, xhr) {
				if (status == "error") {
					if(typeof console != "undefined") {
						console.log(xhr.status + " " + xhr.statusText);
					}
				}
			});
		});

		$("#signupButton").click(function(){
			$.ajax({url:"/Login/signup", 
				
			}).done(function(result){ 

				$("#formSlot").html(result);

			})
			.fail(function(response, status, xhr) {
				if (status == "error") {
					if(typeof console != "undefined") {
						console.log(xhr.status + " " + xhr.statusText);
					}
				}
			});
		});

		$("#glassHex").click(function() {
			$("#glassHex").animate({
				top: '-20px'
			}, 1000, 'linear', function() {
					$("#glassHex h1").css("display", "none");
				}
			)
		});

		$(".button").hover(
			function () {
				$(this).find("input").attr('src', '/images/plainGlassButton.png');
				$(this).find("span").css('color', 'black');
			},
			function () {
				$(this).find("input").attr('src', '/images/blackGlassButton.png');
				$(this).find("span").css('color', 'white');
			}
		);

	});

	</script>

</head>
<body>
	<div id="glassHex">
		<img src="/images/glassHex.png">
		<h1>
			<!--<span class="log-in">Log in</span> or <span class="sign-up">sign up</span>-->
			<div class="button" id="loginButton">
				<input type="image" src="/images/blackGlassButton.png" alt="Submit">
				<span class="log-in">Login</span>
			</div>
			<div class="button" id="signupButton">
				<input type="image" src="/images/blackGlassButton.png" alt="Submit">
				<span class="sign-up">signup</span>
			</div>
		</h1>
	</div>
	<div id="formSlot">
	</div>
</body>
