<head>
	<title>Stubees</title>
	<style>
		html { 
		  background: url('./images/stubeesWall.jpg') no-repeat ; 
		  -webkit-background-size: cover;
		  -moz-background-size: cover;
		  -o-background-size: cover;
		  background-size: cover;
		}
		.r1Div {
            height: 150px; width: 32%; float: left;
        }
        .r2Div {
            height: 400px; width: 32%; float: left;
        }
		.btnDiv{
			height: 100; width: 48%; float: left;
		}
		.btnDivSubmit{
			height: 100px; width: 70%;float: left;
		}
		.btnDivFb{
			height: 50px; width: 30%; float: right;
		}
		.btnMainDiv{
			height: 50px; width: 30%; float: left ;
		}

		#teamMembers {
			position:absolute; bottom:0; text-align:center;
			width:100%;
		}
		
		.circular {
			width: 70px;
			height: 70px;
			border-radius: 150px;
			-webkit-border-radius: 150px;
			-moz-border-radius: 150px;
			box-shadow: 0 0 8px rgba(0, 0, 0, .8);
			-webkit-box-shadow: 0 0 8px rgba(0, 0, 0, .8);
			-moz-box-shadow: 0 0 8px rgba(0, 0, 0, .8);
			display: inline-block;
		}

		.circular img {
			opacity: 0;
			filter: alpha(opacity=0);
		}
		
		/*Button link styles*/
		.button a:link, .button a:visited {
			color: #eee;
			background-color:#1e5184;
			font-size:1em;
			font-weight:bolder;
			text-decoration: none;
			border-bottom:0.1em solid #555;
			border-right:0.1em solid #555;
			border-top:0.1em solid #ccc;
			border-left:0.1em solid #ccc;
			margin: 0.2em;
			padding:0.2em;
			display:block;
		}
		.button a:hover {
			background-color:#003366;
			color:#999;
			border-top:0.1em solid #777;
			border-left:0.1em solid #777;
			border-bottom:0.1em solid #aaa;
			border-right:0.1em solid #aaa;
			padding:0.2em;
			margin: 0.2em;
		}
	</style>
</head>
<body style="height: 100% ;width: 100%;">
		<div id="txtLogs" class="r1Div">
		</div>
		
		<div class="r1Div"></div>

		<div class="r1Div">
			<div class="btnMainDiv">
				
			</div>
			<div class="btnMainDiv">
				<center>
						<?php if ($this->userLoggedIn == "true") {?>
							<span class="button" style="background-color:white;">
							Welcome <?php echo $this->userName; ?>
							</span>
						<?php } else { ?>
							<span class="button">
								<a title="Login" href='<?php echo $this->url(array('controller' => 'Login', 'action' => 'index'), null, false)?>'>
									Login
								</a>
							</span>	
						<?php } ?>
						
						
				</center>
			</div>
			<div class="btnMainDiv">
				<center>
						<?php if ($this->userLoggedIn == "true") { ?>
							<div id=homediv align="right">
								<a href="<?php echo $this->url(array('controller' => 'Login', 'action' => 'logout'), null, false)?>"><img height="45" width="45px" src='<?=$this->baseUrl('images/logoutIcon.png')?>' style="text-decoration:none"></img></a>
							</div>
						<?php } else { ?>	
							<span class="button"> 
							<a title="Sign Up" href='<?php echo $this->url(array('controller' => 'Login', 'action' => 'signup'), null, false)?>'>
								Sign Up
							</a>
							</span>
						<?php } ?>	
				</center>
			</div>
			<div style="height: 75px; width: 31%; float: left">
			</div>
			<div style="height: 75px; width: 55%; float: left">
				<center>
					<a href='<?php echo $this->url(array('controller' => 'Login', 'action' => 'index'), null, false)?>'><img height="75px" width="75px" src="./images/travelApp1.png" style="text-decoration:none"></img></a>
				</center>
			</div>
			
		</div>
		
    <div>
        <div class="r2Div" style="display: inline-block;">
			<div id="teamMembers">
			<div><img src="images/busyBees.png" alt="" style="width:140px;height:60px;"/></div>
			<div class="circular" style="background:url(./images/scooby.jpg) no-repeat;background-size: 70px 70px;"><img src="images/scooby.jpg" alt="" /></div>
			<div class="circular" style="background:url(./images/tintin.jpg) no-repeat;background-size: 70px 70px;"><img src="images/tintin.jpg" alt="" /></div>
			<div class="circular" style="background:url(./images/dexter.jpg) no-repeat;background-size: 70px 70px;"><img src="images/dexter.jpg" alt="" /></div>
			<div class="circular" style="background:url(./images/popeye.jpg) no-repeat;background-size: 70px 70px;"><img src="images/popeye.jpg" alt="" /></div>
			<div class="circular" style="background:url(./images/batman.jpg) no-repeat;background-size: 70px 70px;"><img src="images/batman.jpg" alt="" /></div>
			</div>
        </div>
        <div class="r2Div">
        </div>
		<div class="r2Div">
		</div>
    </div>
</body>
