<div id=homediv align="right">
	<a href='<?php echo $this->url(array('controller' => 'Index', 'action' => 'index'), null, false)?>'><img height="75px" width="75px" src="<?=$this->baseUrl('images/home.jpg')?>" style="text-decoration:none"></img></a>
</div>

<div id=centerdiv >
	<?php if($this->sendValidateEmail) : ?>
		<center>
		<p>Welcome to Travel App</p>
		</center>
		Your Email is Not validated.<br />
		<a href='<?php echo $this->url(array('controller' => 'Login', 'action' => 'useremailvalidation'), null, false)?>?uuid=aaa
		&pid=<?php echo $this->userIndex ?>'>
		<button type="button"> Resend Email</button></a>
	<?php endif; ?>
	<?php if($this->loginFailed) {?>
	<div>
		<center>
			<font color='red'>Login Failed</font>
		</center>
	</div>
<?php }else{ ?>
		<div id=homediv align="right">
			<a href="<?php echo $this->url(array('controller' => 'Login', 'action' => 'index'), null, false)?>" onclick="FB.logout();"><img height="45" width="45px" src='<?=$this->baseUrl('images/logoutIcon.png')?>' style="text-decoration:none"></img></a>
		</div>
		<h3>Welcome <?php echo $this->userFirstName ;?> <?php echo $this->userLastName ;?></h3> <br/>
		<h3>E-Mail: <?php echo $this->userEMail ;?></h3>

<?php } ?>
</div>
<!-- Setting uuid to aaa so that handling in the action can be easy -->
