<style type="text/css">

html { 
	background: url('<?=$this->baseUrl('images/chalkWallPlain.jpg')?>') no-repeat ; 
	-webkit-background-size: cover;
	-moz-background-size: cover;
	-o-background-size: cover;
	background-size: cover;
}

#homediv{
	height: 85px; width: 100%; float: right;
	}
.btnDiv{
	height: 100; width: 40%; float: left;
	}
#centerdiv {     
	width:700px;
	height:250px;
	position:absolute;
	left:50%;
	top:50%;
	margin:-125px 0 0 -350px; 
	background-color:white;
	border-width:3px;
	border-style:solid;
	border-color:blue
}

#teamMembers {
	position:absolute; bottom:0; text-align:center;
	width:100%;
}
		
.circular {
	width: 70px;
	height: 70px;
	border-radius: 150px;
	-webkit-border-radius: 150px;
	-moz-border-radius: 150px;
	box-shadow: 0 0 8px rgba(0, 0, 0, .8);
	-webkit-box-shadow: 0 0 8px rgba(0, 0, 0, .8);
	-moz-box-shadow: 0 0 8px rgba(0, 0, 0, .8);
	display: inline-block;
}

.circular img {
	opacity: 0;
	filter: alpha(opacity=0);
}

/*Button link styles*/
		.button a:link, .button a:visited {
			color: #eee;
			background-color:#1e5184;
			font-size:1em;
			font-weight:bolder;
			text-decoration: none;
			border-bottom:0.1em solid #555;
			border-right:0.1em solid #555;
			border-top:0.1em solid #ccc;
			border-left:0.1em solid #ccc;
			margin: 0.2em;
			padding:0.2em;
			display:block;
		}
		.button a:hover {
			background-color:#003366;
			color:#999;
			border-top:0.1em solid #777;
			border-left:0.1em solid #777;
			border-bottom:0.1em solid #aaa;
			border-right:0.1em solid #aaa;
			padding:0.2em;
			margin: 0.2em;
		}
</style>

<div id=homediv align="right">
	<a href='<?php echo $this->url(array('controller' => 'Index', 'action' => 'index'), null, false)?>'><img height="75px" width="75px" src="<?=$this->baseUrl('images/home.jpg')?>" style="text-decoration:none"></img></a>
</div>

<div id=centerdiv >
	<?php if($this->loginFailed) {?>
		<div>
			<center>
				<font color='red'>Login Failed</font>
			</center>
		</div>
		</div>
	<?php }else{ ?>
			<center>
			<h3>Welcome <?php echo $this->userFirstName ;?> <?php echo $this->userLastName ;?></h3> <br/>
			</center>
			
			
	<?php } ?>

	<?php if($this->sendValidateEmail) : ?>
		
		Your Email is Not validated.<br />
		<div class="btnDiv">
			<span class="button"> 
				<a title="Resend Email" href='<?php echo $this->url(array('controller' => 'Login', 'action' => 'useremailvalidation'), null, false)?>?uuid=aaa&pid=<?php echo $this->userIndex ?>'>
					 Resend Email
				</a>
			</span>
		</div>	
	<?php endif; ?>
	</div>
	
	<?php if(!$this->loginFailed) {?>
	<div id=homediv align="right">
		<a href="<?php echo $this->url(array('controller' => 'Login', 'action' => 'logout'), null, false)?>"><img height="45" width="45px" src='<?=$this->baseUrl('images/logoutIcon.png')?>' style="text-decoration:none"></img></a>
	</div>
	<?php } ?>
<!-- Setting uuid to aaa so that handling in the action can be easy -->

<div>
	<div class="r2Div" style="display: inline-block;">
	<center>
		<div id="teamMembers">
		<div><img src="<?=$this->baseUrl('images/busyBees.png')?>" alt="" style="width:140px;height:60px;"/></div>
		<div class="circular" style="background:url(<?=$this->baseUrl('images/scooby.jpg')?>) no-repeat;background-size: 70px 70px;"><img src="images/scooby.jpg" alt="" /></div>
		<div class="circular" style="background:url(<?=$this->baseUrl('images/tintin.jpg')?>) no-repeat;background-size: 70px 70px;"><img src="images/tintin.jpg" alt="" /></div>
		<div class="circular" style="background:url(<?=$this->baseUrl('images/dexter.jpg')?>) no-repeat;background-size: 70px 70px;"><img src="images/dexter.jpg" alt="" /></div>
		<div class="circular" style="background:url(<?=$this->baseUrl('images/popeye.jpg')?>) no-repeat;background-size: 70px 70px;"><img src="images/popeye.jpg" alt="" /></div>
		<div class="circular" style="background:url(<?=$this->baseUrl('images/batman.jpg')?>) no-repeat;background-size: 70px 70px;"><img src="images/batman.jpg" alt="" /></div>
		</div>
	</center>
	</div>
</div>