
<style type="text/css">
	html { 
		  background:  url('<?=$this->baseUrl('images/chalkWallPlain.jpg')?>') no-repeat ; 
		  -webkit-background-size: cover;
		  -moz-background-size: cover;
		  -o-background-size: cover;
		  background-size: cover;
	}
	.error
	{ color:red; }

	#centerdiv {     
		width:600px;
		height:400px;
		position:absolute;
		left:50%;
		top:35%;
		margin:-100px 0 0 -300px; 
		background-color:white;
		border-width:3px;
		border-style:solid;
		border-color:blue;
	}
	
	#centerdiv_login {     
		width:600px;
		height:200px;
		position:absolute;
		left:50%;
		top:50%;
		margin:-100px 0 0 -300px; 
		background-color:white;
		border-width:3px;
		border-style:solid;
		border-color:blue;
	}
	
	.r2Div {
        height: 400px; width: 90%; float: left;
    }
	#divHeading {
		text-align:center;
		text-emphasis-style:filled;
		text-decoration:solid;
		
	}
	#homediv{
		height: 85px; width: 100%; float: right;
	}
	.btnDiv{
			height: 100; width: 40%; float: left;
		}
		
	#teamMembers {
		position:absolute; bottom:0; text-align:center;
		width:100%;
	}
		
	.circular {
		width: 70px;
		height: 70px;
		border-radius: 150px;
		-webkit-border-radius: 150px;
		-moz-border-radius: 150px;
		box-shadow: 0 0 8px rgba(0, 0, 0, .8);
		-webkit-box-shadow: 0 0 8px rgba(0, 0, 0, .8);
		-moz-box-shadow: 0 0 8px rgba(0, 0, 0, .8);
		display: inline-block;
	}

	.circular img {
		opacity: 0;
		filter: alpha(opacity=0);
	}
	
	/*Button link styles*/
		.button a:link, .button a:visited {
			color: #eee;
			background-color:#1e5184;
			font-size:1em;
			font-weight:bolder;
			text-decoration: none;
			border-bottom:0.1em solid #555;
			border-right:0.1em solid #555;
			border-top:0.1em solid #ccc;
			border-left:0.1em solid #ccc;
			margin: 0.2em;
			padding:0.2em;
			display:block;
		}
		.button a:hover {
			background-color:#003366;
			color:#999;
			border-top:0.1em solid #777;
			border-left:0.1em solid #777;
			border-bottom:0.1em solid #aaa;
			border-right:0.1em solid #aaa;
			padding:0.2em;
			margin: 0.2em;
		}
		
		#email {
			border:2px solid #456879;
			border-radius:10px;
			height: 22px;
			width: 230px;
		}
		
		#password {
			border:2px solid #456879;
			border-radius:10px;
			height: 22px;
			width: 230px;
		}
		
		#submit{
			color: #eee;
			background-color:#1e5184;
			font-size:1em;
			font-weight:bolder;
			text-decoration: none;
			border-bottom:0.1em solid #555;
			border-right:0.1em solid #555;
			border-top:0.1em solid #ccc;
			border-left:0.1em solid #ccc;
			margin: 0.2em;
			padding:0.2em;
			display:block;
		}
		#submit a:hover {
			background-color:#003366;
			color:#999;
			border-top:0.1em solid #777;
			border-left:0.1em solid #777;
			border-bottom:0.1em solid #aaa;
			border-right:0.1em solid #aaa;
			padding:0.2em;
			margin: 0.2em;
		}
		
</style>

<script>
$(document).ready(function(){
	$("input").focus(function(){
    $(this).css("background-color","#cccccc");
  	});
  	$("input").blur(function(){
    $(this).css("background-color","#ffffff");
  	});

  	var email = $("#email");
  	var emailDetails = $("#emailDetails");
  	var password = $("#password");
  	var passwordDetails = $("#passwordDetails");
  	var submit = $("#submit");

  	email.blur(validateEmail);
  	password.blur(validatePassword);
	
  	email.keyup(validateEmail);
  	password.keyup(validatePassword);

  	$(this).submit(function(){
		if(validateEmail() & validatePassword()) {
			return true;
		} else {
			return false;
		}	
  	});  	

	function validateEmail() {
		var myEmail = $("#email").val();
		var myRegex = /^[a-zA-Z0-9]+[a-zA-Z0-9_.-]+[a-zA-Z0-9_­-]+@[a-zA-Z0-9]+[a-zA-Z0-9.-]+[a-zA-Z0-9­]+.[a-z]{2,4}$/;
		if (myRegex.test(myEmail)) {
			email.removeClass("error");
			emailDetails.text("So we can validate you");
			emailDetails.removeClass("error");
			return true;
		} else {
			email.addClass("error");
			emailDetails.text("Please enter valid email id");
			emailDetails.addClass("error");
			return false;
		}	
	}

	function validatePassword () {
		if (password.val().length >= 8) {
			password.removeClass("error");
			passwordDetails.text("Password must be a minimum of 8 characters");
			passwordDetails.removeClass("error");
			return true;
		} else {
			password.addClass("error");
			passwordDetails.text("8 or more characters please!");
			passwordDetails.addClass("error");
			return false;
		}
	}		
});

</script>

<script>
	function checkFBLoginStatus() {
			fbAsyncLoad(document, 'script', 'facebook-jssdk');
			//window.fbAsyncInit();
			FB.login(function(response){
				if(response.authResponse) {
					document.location="http://stubees.com/popeye/public/Login/fblogin";
				}
			},{scope:'email'});
	}
</script>

<?php if (!$this->fbUser && !$this->regularUser) { ?>
	<div id=homediv align="right">
		<a href='<?php echo $this->url(array('controller' => 'Index', 'action' => 'index'), null, false)?>'><img height="75px" width="75px" src='<?=$this->baseUrl('images/home.jpg')?>' style="text-decoration:none"></img></a>
	</div>
	<div id=centerdiv_login>
		<?php if(isset($this->errorMessage)){ echo $this->errorMessage; }?>
		<div>
			<div style="height: 110px; width: 80% ;float: left">
			<?php echo $this->form; ?>
			</div>
			<div style="height: 110px; width: 15% ;float: left;top:50%;margin:30px 0 0 0;">
			<center>
				<a id=fbButton href="<?php echo $this->url(array('controller' => 'Login', 'action' => 'fblogin'), null, false)?>" onclick="checkFBLoginStatus();return false;" style="text-decoration:none"><img height="60px" width="60px" src= '<?=$this->baseUrl('images/fbLogo.png')?>' style="text-decoration:none"></img></a>
			</center>
			</div>
		</div>
		<div class="btnDiv">
			<center>
				<span class="button"> 
				<a title="Sign Up" href='<?php echo $this->url(array('controller' => 'Login', 'action' => 'signup'), null, false)?>'>
					New user? Sign up here 
				</a>
				</span>
			</center>
		</div>
		<div class="btnDiv">
			<center>
				<span class="button"> 
				<a title="Forgot Password" href='<?php echo $this->url(array('controller' => 'Login', 'action' => 'resetpwd'), null, false)?>'>
					Forgot Password ? 
				</a>
				</span>
			</center>
		</div>
	</div>
<?php }?>
<?php if ($this->fbUser) { ?>
		<div id=homediv align="right">
			<a href='<?php echo $this->url(array('controller' => 'Index', 'action' => 'index'), null, false)?>'><img height="75px" width="75px" src='<?=$this->baseUrl('images/home.jpg')?>' style="text-decoration:none"></img></a>
		</div>

		<div id=homediv align="right">
			<a href="<?php echo $this->url(array('controller' => 'Login', 'action' => 'logout'), null, false)?>"><img height="45" width="45px" src='<?=$this->baseUrl('images/logoutIcon.png')?>' style="text-decoration:none"></img></a>
		</div>
		
		<div id=centerdiv >
			<center>
				<h3>Welcome Fb User Mr. <?php echo $this->userFirstName ;?> <?php echo $this->userLastName ;?></h3> <br/>
			</center>
		</div>
<?php } elseif ($this->regularUser) { ?>
		<div id=homediv align="right">
			<a href='<?php echo $this->url(array('controller' => 'Index', 'action' => 'index'), null, false)?>'><img height="75px" width="75px" src='<?=$this->baseUrl('images/home.jpg')?>' style="text-decoration:none"></img></a>
		</div>

		<div id=homediv align="right">
			<a href="<?php echo $this->url(array('controller' => 'Login', 'action' => 'logout'), null, false)?>"><img height="45" width="45px" src='<?=$this->baseUrl('images/logoutIcon.png')?>' style="text-decoration:none"></img></a>
		</div>
		<div id=centerdiv >
			<center>
				<h3>Welcome <?php echo $this->userFirstName ;?> <?php echo $this->userLastName ;?></h3> <br/>
			</center>
		</div>
<?php } ?>


<div class="r2Div" style="display: inline-block;">
<center>
	<div id="teamMembers">
	<div><img src='<?=$this->baseUrl('images/busyBees.png')?>' alt="" style="width:140px;height:60px;"/></div>
	<div class="circular" style="background: url('<?=$this->baseUrl('images/scooby.jpg')?>') no-repeat;background-size: 70px 70px;"><img src="images/scooby.jpg" alt="" /></div>
	<div class="circular" style="background: url('<?=$this->baseUrl('images/tintin.jpg')?>') no-repeat;background-size: 70px 70px;"><img src="images/tintin.jpg" alt="" /></div>
	<div class="circular" style="background: url('<?=$this->baseUrl('images/dexter.jpg')?>') no-repeat;background-size: 70px 70px;"><img src="images/dexter.jpg" alt="" /></div>
	<div class="circular" style="background: url('<?=$this->baseUrl('images/popeye.jpg')?>') no-repeat;background-size: 70px 70px;"><img src="images/popeye.jpg" alt="" /></div>
	<div class="circular" style="background: url('<?=$this->baseUrl('images/batman.jpg')?>') no-repeat;background-size: 70px 70px;"><img src="images/batman.jpg" alt="" /></div>
	</div>
</center>
</div>
</div>
<script>
	  window.fbAsyncInit = function() {
		FB.init({
		  appId      : '190385524450312', // App ID
		  channelUrl : 'http://stubees.com/popeye/public/Login/fblogin', // Channel File
		  status     : true, // check login status
		  cookie     : true, // enable cookies to allow the server to access the session
		  xfbml      : true  // parse XFBML
		});
		FB.Event.subscribe('auth.login', function(response) {
			window.location.reload();
		});
		FB.Event.subscribe('auth.logout', function(response) {
			window.location.reload();
		});
	  };
	  // Load the SDK Asynchronously
	  fbAsyncLoad(document, 'script', 'facebook-jssdk');
	  function fbAsyncLoad(d, s, id){
		 var js, fjs = d.getElementsByTagName(s)[0];
		 if (d.getElementById(id)) {return;}
		 js = d.createElement(s); js.id = id;
		 js.src = "//connect.facebook.net/en_US/all.js";
		 fjs.parentNode.insertBefore(js, fjs);
	   };
</script>
