<script>
$(document).ready(function(){

	// AJAX START

	$.ajaxSetup ({
		cache: false
	});

	$("#signupButton button").click(function(){
		$.ajax({url:"/Login/signup", 
			
		}).done(function(result){ 

			$("#formSlot").html(result);

		})
		.fail(function(response, status, xhr) {
			if (status == "error") {
				if(typeof console != "undefined") {
					console.log(xhr.status + " " + xhr.statusText);
				}
			}
		});
	});

	$("#forgotPwdButton button").click(function(){
		$.ajax({url:"/Login/resetpwd", 
			
		}).done(function(result){ 

			$("#formSlot").html(result);

		})
		.fail(function(response, status, xhr) {
			if (status == "error") {
				if(typeof console != "undefined") {
					console.log(xhr.status + " " + xhr.statusText);
				}
			}
		});
	});


	// AJAX END

	$("input").focus(function(){
    $(this).css("background-color","#cccccc");
  	});
  	$("input").blur(function(){
    $(this).css("background-color","#ffffff");
  	});

  	var email = $("#email");
  	var emailDetails = $("#emailDetails");
  	var password = $("#password");
  	var passwordDetails = $("#passwordDetails");
  	var submit = $("#submit");

  	email.blur(validateEmail);
  	password.blur(validatePassword);
	
  	email.keyup(validateEmail);
  	password.keyup(validatePassword);

  	$(this).submit(function(){
		if(validateEmail() & validatePassword()) {
			return true;
		} else {
			return false;
		}	
  	});  	

	function validateEmail() {
		var myEmail = $("#email").val();
		var myRegex = /^[a-zA-Z0-9]+[a-zA-Z0-9_.-]+[a-zA-Z0-9_­-]+@[a-zA-Z0-9]+[a-zA-Z0-9.-]+[a-zA-Z0-9­]+.[a-z]{2,4}$/;
		if (myRegex.test(myEmail)) {
			email.removeClass("error");
			emailDetails.text("So we can validate you");
			emailDetails.removeClass("error");
			return true;
		} else {
			email.addClass("error");
			emailDetails.text("Please enter valid email id");
			emailDetails.addClass("error");
			return false;
		}	
	}

	function validatePassword () {
		if (password.val().length >= 8) {
			password.removeClass("error");
			passwordDetails.text("Password must be a minimum of 8 characters");
			passwordDetails.removeClass("error");
			return true;
		} else {
			password.addClass("error");
			passwordDetails.text("8 or more characters please!");
			passwordDetails.addClass("error");
			return false;
		}
	}		
});

/*
FB.logout(function(response) {
	alert("Session is destroyed");
	<?php Zend_Session::destroy( true ); ?>
});
FB.login(function(response) {
   // handle the response
 }, {scope: 'email'});
*/

</script>

<?php if(isset($this->errorMessage)){ echo $this->errorMessage; }?>

<?php if (!$this->user && !$this->regularUser): ?>

<div id=homediv align="right">
	<a href='<?php echo $this->url(array('controller' => 'Index', 'action' => 'index'), null, false)?>'>
		<img height="75px" width="75px" src='<?=$this->baseUrl('images/home.jpg')?>' style="text-decoration:none"></img>
	</a>
</div>

<div id=centerdiv_login>
	<div>
		<div style="height: 110px; width: 80% ;float: left">
		<?php echo $this->form; ?>
		</div>
		<div style="height: 110px; width: 15% ;float: left;top:50%;margin:30px 0 0 0;">
			<center>
				<a href="" onclick="FB.login(function(response){},{scope:'email'});" style="text-decoration:none">
					<img height="60px" width="60px" src= '<?=$this->baseUrl('images/fbLogo.png')?>' style="text-decoration:none"></img>
				</a>
			</center>
		</div>
	</div>
	
	<div class="btnDiv" id="signupButton">
		<center>
			<span class="button"> 
				<button type="button">New user? Sign up here</button>
			</span>
		</center>
	</div>
		
	<div class="btnDiv" id="forgotPwdButton">
		<center>
			<span class="button"> 
				<button type="button">Forgot Password ?</button>
			</span>
		</center>
	</div>

	<?php if($this->loginFailed): ?>
		<div>
			<font color='red'>Login Failed</font>
		</div>
	<?php endif; ?>
</div>

<?php endif; ?>


<?php if ($this->user): ?>
	<div id="homediv" align="right">
		<a href='<?php echo $this->url(array('controller' => 'Index', 'action' => 'index'), null, false)?>'>
			<img height="75px" width="75px" src='<?=$this->baseUrl('images/home.jpg')?>' style="text-decoration:none"></img>
		</a>
	</div>

	<div id="homediv" align="right">
		<a href="<?php echo $this->url(array('controller' => 'Login', 'action' => 'index'), null, false)?>" onclick="FB.logout();">
			<img height="45" width="45px" src='<?=$this->baseUrl('images/logoutIcon.png')?>' style="text-decoration:none"></img>
		</a>
	</div>

	<div id="centerdiv">
		<h3>Welcome <?php echo $this->userFirstName; ?> <?php echo $this->userLastName; ?></h3> <br/>
		<h3>Photo: <img src=<?php echo $this->userPic ;?>></h3>
		<h3>E-Mail: <?php echo $this->userEMail ;?></h3>
		<h3>ID: <?php echo $this->userId ;?></h3>
		<h3>Gender: <?php echo $this->userGender ;?></h3>
		<pre><?php print_r($this->user_profile); ?></pre>
	</div>

<?php elseif ($this->regularUser): ?>
		
	<div id="homediv" align="right">
		<a href='<?php echo $this->url(array('controller' => 'Index', 'action' => 'index'), null, false)?>'>
			<img height="75px" width="75px" src='<?=$this->baseUrl('images/home.jpg')?>' style="text-decoration:none"></img>
		</a>
	</div>

	<div id="homediv" align="right">
		<a href="<?php echo $this->url(array('controller' => 'Login', 'action' => 'index'), null, false)?>" onclick="FB.logout();">
			<img height="45" width="45px" src='<?=$this->baseUrl('images/logoutIcon.png')?>' style="text-decoration:none"></img>
		</a>
	</div>
	
	<div id="centerdiv" >
		<p>WELCOME!!</p>
		<h3>Welcome <?php echo $this->userFirstName ;?> <?php echo $this->userLastName ;?></h3> <br/>
		<h3>E-Mail: <?php echo $this->userEMail ;?></h3>
	</div>

<?php endif; ?>

<!--
<script>
	
          window.fbAsyncInit = function() {
            FB.init({
              appId      : '343333115786778', // App ID
              channelUrl : 'http://stubees.com/scooby/public/Login/', // Channel File
              status     : true, // check login status
              cookie     : true, // enable cookies to allow the server to access the session
              xfbml      : true  // parse XFBML
            });
	        FB.Event.subscribe('auth.login', function(response) {
	        	window.location.reload();
	        });
	        FB.Event.subscribe('auth.logout', function(response) {
		    	// window.location.reload();
		    });
			
          };
          // Load the SDK Asynchronously
          (function(d, s, id){
             var js, fjs = d.getElementsByTagName(s)[0];
             if (d.getElementById(id)) {return;}
             js = d.createElement(s); js.id = id;
             js.src = "//connect.facebook.net/en_US/all.js";
             fjs.parentNode.insertBefore(js, fjs);
           }(document, 'script', 'facebook-jssdk'));
    
</script>
-->
