<style type="text/css">
.error
{ color:red; }
html { 
	background: url('<?=$this->baseUrl('images/chalkWallPlain.jpg')?>') no-repeat ; 
	-webkit-background-size: cover;
	-moz-background-size: cover;
	-o-background-size: cover;
	background-size: cover;
}

#homediv{
		height: 85px; width: 100%; float: right;
	}
#centerdiv {     
		width:700px;
		height:275px;
		position:absolute;
		left:50%;
		top:50%;
		margin:-125px 0 0 -350px; 
		background-color:white;
		border-width:3px;
		border-style:solid;
		border-color:blue
}
</style>
<script>
$(document).ready(function(){

	var password = $("#password");
	var retypePassword = $("#retypePassword");

  	var passwordDetails = $("#passwordDetails");
  	var retypePasswordDetails = $("#retypePasswordDetails");

  	var submit = $("#submit");

  	password.blur(validatePassword);
  	retypePassword.blur(validateRetypePassword);

  	password.keyup(validatePassword);
  	retypePassword.keyup(validateRetypePassword);
	
  	$(this).submit(function(){
		if(validatePassword() & validateRetypePassword() ) {
			return true;
		} else {
			return false;
		}	
  	});  	

	function validatePassword () {
		if (password.val().length >= 8) {
			password.removeClass("error");
			passwordDetails.text("Must be 8 or more characters");
			passwordDetails.removeClass("error");
			return true;
		} else {
			password.addClass("error");
			passwordDetails.text("8 or more characters please!");
			passwordDetails.addClass("error");
			return false;
		}
	}
	function validateRetypePassword () {
		if ((password.val() === retypePassword.val()) && (password.val()!= "")) {
			retypePassword.removeClass("error");
			retypePasswordDetails.text("Re-enter the password");
			retypePasswordDetails.removeClass("error");
			return true;
		} else {
			retypePassword.addClass("error");
			retypePasswordDetails.text("Passwords do not match!");
			retypePasswordDetails.addClass("error");
			return false;
		}
	}		
});
</script>

<div id=homediv align="right">
	<a href='<?php echo $this->url(array('controller' => 'Index', 'action' => 'index'), null, false)?>'><img height="75px" width="75px" src="<?=$this->baseUrl('images/home.jpg')?>" style="text-decoration:none"></img></a>
</div>

<div id=centerdiv >
<?php echo $this->form; ?>
 <?php if($this->succesFlag) : ?>
	   Password Succefully reset
<?php endif; ?>
</div>
