<style type="text/css">
html { 
	background: url('<?=$this->baseUrl('images/chalkWallPlain.jpg')?>') no-repeat ; 
	-webkit-background-size: cover;
	-moz-background-size: cover;
	-o-background-size: cover;
	background-size: cover;
}

#homediv{
		height: 85px; width: 100%; float: right;
	}
</style>
<div id=homediv align="right">
	<a href='<?php echo $this->url(array('controller' => 'Index', 'action' => 'index'), null, false)?>'><img height="75px" width="75px" src="<?=$this->baseUrl('images/home.jpg')?>" style="text-decoration:none"></img></a>
</div>
<?php echo $this->form; ?>
 <?php if($this->succesFlag) : ?>
	   Password Succefully reset
<?php endif; ?>
