<div id=homediv align="right">
	<a href='<?php echo $this->url(array('controller' => 'Index', 'action' => 'index'), null, false)?>'><img height="75px" width="75px" src="<?=$this->baseUrl('images/home.jpg')?>" style="text-decoration:none"></img></a>
</div>
<!--  Flag set implies user has already entered a valid email, so display link to main page -->
<div id=centerdiv >
<?php 
    if($this->flag == 0)
	{
	   echo $this->errormsg;
	   echo $this->form; 
	   return;
	}
?>

	<div id="view-content">
		<p>A email has been sent to you with the link to reset your password</p>
	</div>

	
</div>
