<div id="homediv" align="right">
	<a href='<?php echo $this->url(array('controller' => 'Index', 'action' => 'index'), null, false)?>'><img height="75px" width="75px" src="<?=$this->baseUrl('images/home.jpg')?>" style="text-decoration:none"></img></a>
</div>

<div id="centerdiv" >
<?php if($this->sendValidateEmail) : ?>
	   An email has been sent
<?php endif; ?>

 <?php 
 if(isset($this->errorMessage))
 {
 	echo $this->errorMessage;
 }
 echo $this->form; 
 ?>
<?php if($this->goHomeFlag) : ?>
     Your Account is already validated
<?php endif; ?>
</div>
 